spring:
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://82.157.30.217:5432/postgres?ssl=false&socketTimeout=30&connectTimeout=30
    username: postgres
    password: XXX
  hikari:                           #数据源的配置信息
    connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
    minimum-idle: 5                 # 最小连接数
    maximum-pool-size: 20           # 最大连接数
    auto-commit: true               # 自动提交
    idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    pool-name: DateSourceHikariCP   # 连接池名字
    max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
    connection-test-query: SELECT 1
  data:
    redis:
      password: XXX   # 密码
      host: 117.72.109.137  # 地址
      port: 6379  # 端口号
      database: 0  # 数据库索引（默认为0）
      timeout: 1800000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1  # 最大阻塞等待时间（负数表示没有限制）
          max-idle: 5  # 连接池中最大空闲连接
          min-idle: 0  # 连接池中最小空闲连接

--- #位置
hip:
  url: /home/ubuntu/ai-teaching-video/